<a href="https://colab.research.google.com/github/ipaliotti/MLPNS_IPaliotti/blob/main/MLPNS23_bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
    2*2


4

In [2]:
2*2

4

#First markdown cell
this is a text cell in markdown syntax


#Here we start coding


#Native variables and variables types

Una variabile è un pezzo di memoria che ha dei valori specifici. 
I tipi di varibaile corrispondono ai tipi di dati che abbiamo, dal punto di vista del computer è quanti bytes occupa.

##interi


In [3]:
intVar=3

type(intVar)


int

##float


In [4]:
floatVar=3.0

In [5]:
type(floatVar)

float

In [6]:

float2Var=float(intVar)
type(float2Var)

float

In [7]:
intVar*floatVar


9.0

In [8]:
intVar*floatVar == 9

True

In [9]:
intVar/2


1.5

In [10]:
intVar+floatVar

6.0

In [11]:
type(intVar + floatVar - intVar/2)

float

In [12]:
intVar + floatVar - intVar/2

4.5

##string

Un altro tipo di variabili sono le stringvariables in pyt.


In [13]:
print("Hello world")

Hello world


Pyton usa o " o ' senza differenza. I colori descrivono le parti di codice che sto usano, arancione sono le funzioni native. le stringhe tra le "" sono sempre in rosso. 
Se metto ''' il carattere new line viene interpretato nella stringa.

In [14]:
print('''Hello 
word''')

Hello 
word


In [15]:
strVar='Hello world'

In [16]:
print(strVar)

Hello world


##boolean variables

Solo true e false 
Se lo scirvo con la maiuscola pyt ce lo ha già come variabile

In [17]:
True

True

In [18]:
False

False

In [19]:
intVar == floatVar

True

In [20]:
if intVar > floatVar:
  print("this is true")
else:
  print("condition was false")

condition was false


In [21]:
# == is equal?
print(intVar==floatVar)
# > greater
print(intVar>floatVar)
# < smaller
print(intVar < floatVar)
# != is not equal
print(intVar!=floatVar)

True
False
False
False


In [22]:
# | is logical OR
(intVar == floatVar) | (intVar>floatVar)
# & is logical AND
(intVar == floatVar) & (intVar>floatVar)

False

In [23]:
True == 1


True

In [24]:
False == 0


True

In [25]:
# ? is logical  AND
if (intVar == floatVar) * (intVar>floatVar):
  print("True")
else:
    print("False")

False


In [26]:
# ? is logical  OR
if (intVar == floatVar) + (intVar>floatVar):
  print("True")
else:
    print("False")

True


In [27]:
#loop: for, while
#range è una funzione, finisce un numero prima e inizia da zero se non specificatp
#il primo valore. Pyt in generale esclude l'ultimo valore. Posso dargli dei salti, ad esempio 2

for i in range(1, 10, 2):
  print(i)

1
3
5
7
9


#Variable as object
Le variabili hanno anche funzioni, metodi e proprietà associate al tipo di variabile. Si chiamano mettendo il punto dopo il nome della variabile. 

In [28]:
strVar='hello world'

In [29]:
strVar.capitalize()

'Hello world'

In [30]:
strVar.upper()

'HELLO WORLD'

In [31]:
strVar.isdigit()

False

In [32]:
"3".isdigit()

True

In [33]:
floatVar.is_integer()

True

#List


In [34]:
listVar = [intVar, floatVar, strVar, 0, True]
listVar


[3, 3.0, 'hello world', 0, True]

In [35]:
#posso aggiungere robe 
listVar.append(11)
listVar

[3, 3.0, 'hello world', 0, True, 11]

In [36]:
listVar[0]
#il primo elemento è in posizione zero

3

In [37]:
strVar[1]

'e'

In [38]:
'h' in strVar

True

In [39]:
64 in listVar

False

In [40]:
#posso cambiare un elemento della lista ma non della stringa

listVar[2] = 4
listVar

[3, 3.0, 4, 0, True, 11]

#ESERCIZIO 1 "Wordle"

In [41]:
target = 'acres'
guess = 'Acres'
risultato = [0,0,0,0,0]
for i in range(0,5):
    if target[i] in guess:
      for j in range(0,5):
        if (target[i] == guess[j]) & (i==j):
          risultato[j] = target[i] 
        if (target[i] == guess[j]) & (i!=j):
          risultato[j] = '*' 
print(risultato)

      #se ho piu di un alternativa a if posso usare elif
      


[0, 'c', 'r', 'e', 's']


#Fuctions

In [42]:
def wordle(guess):
  '''
  A function that checks a word guess against a target
  Input:
  guess: a string
  Return:
  a string
  '''


##IMPORTING PACKAGES
typical packages that we will see
### pandas 
  manipulation of tabular data
### numpy 
  manipulation of numerical data
### scipy
  statmodels 
### matplotlib
  visualization and plotting
### sklearn 
  machine learning
### tensorflow
  neural networks
  

In [43]:
import pandas as pd

pd.read_csv

from pandas import read_csv

read_csv

##from pandas import * #NEVER!!!


<function pandas.io.parsers.readers.read_csv(filepath_or_buffer: 'FilePathOrBuffer', sep=<no_default>, delimiter=None, header='infer', names=<no_default>, index_col=None, usecols=None, squeeze=False, prefix=<no_default>, mangle_dupe_cols=True, dtype: 'DtypeArg | None' = None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal: 'str' = '.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors: 'str | None' = 'strict', dialect=None, error_bad_lines=None, warn_bad_lines=None, on_bad_lines=None, delim_whitespace=False, low_memory=True, memory_map=False,

In [44]:
url='https://raw.githubusercontent.com/fedhere/PyBOOT/master/311_Service_Requests_from_2010_to_Present.csv'

pd.read_csv(url)

df=pd.read_csv(url)
df.shape


(924, 41)

In [45]:
df.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'BBL', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Open Data Channel Type',
       'Park Facility Name', 'Park Borough', 'Vehicle Type',
       'Taxi Company Borough', 'Taxi Pick Up Location', 'Bridge Highway Name',
       'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment',
       'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [46]:
df


Unique Key            Created Date             Closed Date Agency  \
0      54049402  05/01/2022 12:00:03 AM                     NaN   NYPD   
1      54046813  05/01/2022 12:00:09 AM  05/01/2022 12:07:46 AM   NYPD   
2      54045643  05/01/2022 12:00:17 AM  05/01/2022 12:10:38 AM   NYPD   
3      54051838  05/01/2022 12:00:21 AM  05/01/2022 12:53:23 AM   NYPD   
4      54052808  05/01/2022 12:00:25 AM  05/01/2022 01:01:47 AM   NYPD   
..          ...                     ...                     ...    ...   
919    54049386  05/01/2022 02:04:45 AM                     NaN   NYPD   
920    54049413  05/01/2022 02:05:35 AM                     NaN   NYPD   
921    54052476  05/01/2022 02:05:38 AM                     NaN   NYPD   
922    54053504  05/01/2022 02:06:13 AM                     NaN   NYPD   
923    54048300  05/01/2022 02:06:26 AM                     NaN   NYPD   

                         Agency Name           Complaint Type  \
0    New York City Police Department      Noise - Residential   
1    New York City Police Department  Noise - Street/Sidewalk   
2    New York City Police Department      Noise - Residential   
3    New York City Police Department         Blocked Driveway   
4    New York City Police Department          Illegal Parking   
..                               ...                      ...   
919  New York City Police Department      Noise - Residential   
920  New York City Police Department  Noise - Street/Sidewalk   
921  New York City Police Department      Noise - Residential   
922  New York City Police Department          Illegal Parking   
923  New York City Police Department          Noise - Vehicle   

                       Descriptor               Location Type  Incident Zip  \
0                Loud Music/Party  Residential Building/House       10452.0   
1                Loud Music/Party             Street/Sidewalk       10027.0   
2                Loud Music/Party  Residential Building/House       10033.0   
3                  Partial Access             Street/Sidewalk       11214.0   
4    Commercial Overnight Parking             Street/Sidewalk       10304.0   
..                            ...                         ...           ...   
919              Loud Music/Party  Residential Building/House       10031.0   
920              Loud Music/Party             Street/Sidewalk       11231.0   
921              Loud Music/Party  Residential Building/House       11208.0   
922  Overnight Commercial Storage             Street/Sidewalk       11373.0   
923               Car/Truck Music             Street/Sidewalk       11210.0   

             Incident Address  ... Vehicle Type Taxi Company Borough  \
0          1006 GERARD AVENUE  ...          NaN                  NaN   
1        364 WEST  127 STREET  ...          NaN                  NaN   
2    593 FT WASHINGTON AVENUE  ...          NaN                  NaN   
3              8106 17 AVENUE  ...          NaN                  NaN   
4           935 TARGEE STREET  ...          NaN                  NaN   
..                        ...  ...          ...                  ...   
919      514 WEST  136 STREET  ...          NaN                  NaN   
920       151 RICHARDS STREET  ...          NaN                  NaN   
921         37 HEMLOCK STREET  ...          NaN                  NaN   
922        60-42 BOOTH STREET  ...          NaN                  NaN   
923      723 EAST   27 STREET  ...          NaN                  NaN   

    Taxi Pick Up Location Bridge Highway Name Bridge Highway Direction  \
0                     NaN                 NaN                      NaN   
1                     NaN                 NaN                      NaN   
2                     NaN                 NaN                      NaN   
3                     NaN                 NaN                      NaN   
4                     NaN                 NaN                      NaN   
..                    ...                 ...                      ...   
919

In [47]:
df.iloc[0]

Unique Key                                                       54049402
Created Date                                       05/01/2022 12:00:03 AM
Closed Date                                                           NaN
Agency                                                               NYPD
Agency Name                               New York City Police Department
Complaint Type                                        Noise - Residential
Descriptor                                               Loud Music/Party
Location Type                                  Residential Building/House
Incident Zip                                                      10452.0
Incident Address                                       1006 GERARD AVENUE
Street Name                                                 GERARD AVENUE
Cross Street 1                                           EAST  164 STREET
Cross Street 2                                           EAST  165 STREET
Intersection Street 1                 

In [48]:
df.iloc[:, 1]#estrai tutte le colonne

0      05/01/2022 12:00:03 AM
1      05/01/2022 12:00:09 AM
2      05/01/2022 12:00:17 AM
3      05/01/2022 12:00:21 AM
4      05/01/2022 12:00:25 AM
                ...          
919    05/01/2022 02:04:45 AM
920    05/01/2022 02:05:35 AM
921    05/01/2022 02:05:38 AM
922    05/01/2022 02:06:13 AM
923    05/01/2022 02:06:26 AM
Name: Created Date, Length: 924, dtype: object

In [49]:
url='https://raw.githubusercontent.com/fedhere/UInotebooks/master/dataWrangling/movies.dat'


In [50]:
colnames=["title","genre"]
movies=pd.read_csv(url, sep="::", index_col=0, header=None, names=colnames);

/usr/local/lib/python3.9/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


In [51]:
movies.shape

(3883, 2)

In [52]:
movies.columns

Index(['title', 'genre'], dtype='object')

In [53]:
movies['title']

1                         Toy Story (1995)
2                           Jumanji (1995)
3                  Grumpier Old Men (1995)
4                 Waiting to Exhale (1995)
5       Father of the Bride Part II (1995)
                       ...                
3948               Meet the Parents (2000)
3949            Requiem for a Dream (2000)
3950                      Tigerland (2000)
3951               Two Family House (2000)
3952                 Contender, The (2000)
Name: title, Length: 3883, dtype: object

In [54]:
movies.title

1                         Toy Story (1995)
2                           Jumanji (1995)
3                  Grumpier Old Men (1995)
4                 Waiting to Exhale (1995)
5       Father of the Bride Part II (1995)
                       ...                
3948               Meet the Parents (2000)
3949            Requiem for a Dream (2000)
3950                      Tigerland (2000)
3951               Two Family House (2000)
3952                 Contender, The (2000)
Name: title, Length: 3883, dtype: object

In [55]:
movies['title']


1                         Toy Story (1995)
2                           Jumanji (1995)
3                  Grumpier Old Men (1995)
4                 Waiting to Exhale (1995)
5       Father of the Bride Part II (1995)
                       ...                
3948               Meet the Parents (2000)
3949            Requiem for a Dream (2000)
3950                      Tigerland (2000)
3951               Two Family House (2000)
3952                 Contender, The (2000)
Name: title, Length: 3883, dtype: object

In [56]:
" Toy Story (1995)".split()[-1].replace("(","").strip(")")  #posso contare al contrario basta mettere il meno

'1995'

In [57]:
def get_year(mtitle):
  """
  """

  return int(mtitle.split("(")[-1].strip(")"))


In [58]:

movies["title"].map(get_year)

1       1995
2       1995
3       1995
4       1995
5       1995
        ... 
3948    2000
3949    2000
3950    2000
3951    2000
3952    2000
Name: title, Length: 3883, dtype: int64

In [59]:
movies.gruopby("year").count().plot(y="title")

AttributeError: ignored

In [60]:
movies['genres']=movies.genre.map(lambda x: x.split('|'))

In [61]:
movies['genres'] == "Fantasy"

1       False
2       False
3       False
4       False
5       False
        ...  
3948    False
3949    False
3950    False
3951    False
3952    False
Name: genres, Length: 3883, dtype: bool

In [63]:
movies[movies['genres'] == "Fantasy"]

Empty DataFrame
Columns: [title, genre, genres]
Index: []

In [66]:
#regular for loop
glist=[]
for m in movies['genre']:
  print("Fantasy" in m)
  glist.append("Fantasy" in m)



False
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
False
False
False
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
Fa

In [68]:
#list comprehension

["Fantasy" in m for m in movies ['genre']]

movies[["Fantasy" in m for m in movies ['genre']]]

title  \
2                                        Jumanji (1995)   
56                       Kids of the Round Table (1995)   
60                   Indian in the Cupboard, The (1995)   
126                   NeverEnding Story III, The (1994)   
247                           Heavenly Creatures (1994)   
...                                                 ...   
3479                                   Ladyhawke (1985)   
3489                                        Hook (1991)   
3877                                   Supergirl (1984)   
3889                         Highlander: Endgame (2000)   
3920  Faraway, So Close (In Weiter Ferne, So Nah!) (...   

                               genre                               genres  
2       Adventure|Children's|Fantasy     [Adventure, Children's, Fantasy]  
56      Adventure|Children's|Fantasy     [Adventure, Children's, Fantasy]  
60      Adventure|Children's|Fantasy     [Adventure, Children's, Fantasy]  
126     Adventure|Children's|Fantasy     [Adventure, Children's, Fantasy]  
247   Drama|Fantasy|Romance|Thriller  [Drama, Fantasy, Romance, Thriller]  
...                              ...                                  ...  
3479       Adventure|Fantasy|Romance        [Adventure, Fantasy, Romance]  
3489               Adventure|Fantasy                 [Adventure, Fantasy]  
3877        Action|Adventure|Fantasy         [Action, Adventure, Fantasy]  
3889        Action|Adventure|Fantasy         [Action, Adventure, Fantasy]  
3920                   Drama|Fantasy                     [Drama, Fantasy]  

[68 rows x 3 columns]

#Numpy
unico linguaggio che ha un articolo pubblicato su Nature

In [69]:
import numpy as np

In [70]:
#integer and float funzionano ma numpy permette di definire quanti bit associare alla variabile 
a=3
type(a)


int

In [71]:
a = np.int16(3)

In [73]:
a.dtype

dtype('int16')

In [75]:
a = np.int8(3) #max 128 min -128

In [77]:
print(np.uint8(256)) #max 255 min 0

0


In [78]:
#numpy for array 

#in numpy gli array devono essere tutti dello stesso tipo

np.array(glist)

array([False,  True, False, ..., False, False, False])

In [79]:
glist[3:6]  #fino al quinto elemento

[False, False, False]

In [81]:
listVar

[3, 3.0, 4, 0, True, 11]

In [83]:
np.array(listVar)

array([ 3.,  3.,  4.,  0.,  1., 11.])

In [85]:
np.zeros?



In [86]:
np.zeros((10,2), float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [89]:
#posso creare array di valori random che seguano o una gaussiana o una distribuzione uniforme

np.random.rand(10,2) #uniforme
np.random.randn(10,2) #gaussiana


array([[ 0.16334303,  0.12968315],
       [-1.27471179, -0.98603439],
       [-0.76027271,  0.4080377 ],
       [-1.57811115,  0.50540388],
       [-0.50535991,  0.63234793],
       [ 0.71008381, -1.41181361],
       [ 1.31399138,  1.04806099],
       [ 1.49657939, -0.01226278],
       [ 0.26856956,  0.41567452],
       [-0.56676657,  0.51202135]])

In [90]:
randArr=np.random.rand(10,2,3)


In [93]:
randArr[0].shape#estrae la prima colonna


(2, 3)

In [94]:
randArr[1:6].shape #estrae dalla riga 1 alla 5 saltando la zero


(5, 2, 3)

In [95]:
randArr[:,0,:2]


array([[0.10017081, 0.17622009],
       [0.62315096, 0.04074251],
       [0.56138448, 0.06896883],
       [0.6226879 , 0.43501106],
       [0.10763454, 0.10347166],
       [0.09518518, 0.89059495],
       [0.9218873 , 0.74387569],
       [0.15969612, 0.46318248],
       [0.83029959, 0.21976314],
       [0.19191378, 0.61118124]])

In [96]:
randArr[randArr>0].shape

(60,)

In [97]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [99]:
rangeArr1=np.arange(0,10,0.1)

In [102]:
rangeArr1 = rangeArr1.reshape(10,10)

#posso moltiplicare per 2
#nelle liste SONO OPERAZIONI DI CONCATENAZIONE

rangeArr1*rangeArr1 #prodotto elemento/elemento

array([[0.000e+00, 1.000e-02, 4.000e-02, 9.000e-02, 1.600e-01, 2.500e-01,
        3.600e-01, 4.900e-01, 6.400e-01, 8.100e-01],
       [1.000e+00, 1.210e+00, 1.440e+00, 1.690e+00, 1.960e+00, 2.250e+00,
        2.560e+00, 2.890e+00, 3.240e+00, 3.610e+00],
       [4.000e+00, 4.410e+00, 4.840e+00, 5.290e+00, 5.760e+00, 6.250e+00,
        6.760e+00, 7.290e+00, 7.840e+00, 8.410e+00],
       [9.000e+00, 9.610e+00, 1.024e+01, 1.089e+01, 1.156e+01, 1.225e+01,
        1.296e+01, 1.369e+01, 1.444e+01, 1.521e+01],
       [1.600e+01, 1.681e+01, 1.764e+01, 1.849e+01, 1.936e+01, 2.025e+01,
        2.116e+01, 2.209e+01, 2.304e+01, 2.401e+01],
       [2.500e+01, 2.601e+01, 2.704e+01, 2.809e+01, 2.916e+01, 3.025e+01,
        3.136e+01, 3.249e+01, 3.364e+01, 3.481e+01],
       [3.600e+01, 3.721e+01, 3.844e+01, 3.969e+01, 4.096e+01, 4.225e+01,
        4.356e+01, 4.489e+01, 4.624e+01, 4.761e+01],
       [4.900e+01, 5.041e+01, 5.184e+01, 5.329e+01, 5.476e+01, 5.625e+01,
        5.776e+01, 5.929e+01, 6.084e+

Esercizio parole palindrome

#esercizio per casa
create a numpy array containing numbers from 1 to 10
extract only even numbers with boolean operations
reverse it
make all those number odd (hint: you can use use range or np.arange to create the array)

In [104]:
numeri=np.arange(11)
numeri

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#MATPLOTLIB

In [110]:
import matplotlib as pl

In [107]:
pl.rcParams['font.size']=20 #cambia i parametri in maniera permanente


NameError: ignored

In [108]:
myx=np.arange(10)
myy=np.arange(0,100,10)


In [112]:
pl.figure(figsize=(3,3)).add_subplot(1,1,1);

TypeError: ignored